WordApp.class:WordApp.java
	javac WordApp.java
ThreaderController.class:ThreaderController.java
	javac ThreaderController.java
WordPanelController.class:WordPanelController.java
	javac WordPanelController.java
Threader.class:Threader.java
	javac Threader.java
WordDictionary.class:WordDictionary.java
	javac WordDictionary.java
WordPanel.class:WordPanel.java
	javac WordPanel.java
WordRecord.class:WordRecord.java
	javac WordRecord.java
Score.class:Score.java
	javac Globals.java
Difficulty.class:Difficulty.java
	javac Globals.java
WordAppView.class:WordAppView.java
	javac WordAppView.java

	
run:
	java WordApp

clean:
	@rm*.class


